export enum AcceptClaimReason {
  DID_NOT_SHIP_ITEM = "DID_NOT_SHIP_ITEM",
  TOO_TIME_CONSUMING = "TOO_TIME_CONSUMING",
  LOST_IN_MAIL = "LOST_IN_MAIL",
  NOT_ABLE_TO_WIN = "NOT_ABLE_TO_WIN",
  COMPANY_POLICY = "COMPANY_POLICY",
  REASON_NOT_SET = "REASON_NOT_SET",
}
