export enum AcknowledgementType {
  ITEM_RECEIVED = "ITEM_RECEIVED",
  ITEM_NOT_RECEIVED = "ITEM_NOT_RECEIVED",
  DAMAGED = "DAMAGED",
  EMPTY_PACKAGE_OR_DIFFERENT = "EMPTY_PACKAGE_OR_DIFFERENT",
  MISSING_ITEMS = "MISSING_ITEMS",
}
