export enum AcceptClaimType {
  REFUND = "REFUND",
  REFUND_WITH_RETURN = "REFUND_WITH_RETURN",
  PARTIAL_REFUND = "PARTIAL_REFUND",
  REFUND_WITH_RETURN_SHIPMENT_LABEL = "REFUND_WITH_RETURN_SHIPMENT_LABEL",
}
