export enum Action {
  ACKNOWLEDGE_RETURN_ITEM = "ACKNOWLEDGE_RETURN_ITEM",
  ACCEPT_CLAIM = "ACCEPT_CLAIM",
  PROVIDE_EVIDENCE = "PROVIDE_EVIDENCE",
  APPEAL = "APPEAL",
  CANCEL = "CANCEL",
  CHANGE_REASON = "CHANGE_REASON",
  ESCALATE = "ESCALATE",
}
