export enum EvidenceType {
  PROOF_OF_DAMAGE = "PROOF_OF_DAMAGE",
  THIRDPARTY_PROOF_FOR_DAMAGE_OR_SIGNIFICANT_DIFFERENCE = "THIRDPARTY_PROOF_FOR_DAMAGE_OR_SIGNIFICANT_DIFFERENCE",
  DECLARATION = "DECLARATION",
  PROOF_OF_MISSING_ITEMS = "PROOF_OF_MISSING_ITEMS",
  PROOF_OF_EMPTY_PACKAGE_OR_DIFFERENT_ITEM = "PROOF_OF_EMPTY_PACKAGE_OR_DIFFERENT_ITEM",
  PROOF_OF_ITEM_NOT_RECEIVED = "PROOF_OF_ITEM_NOT_RECEIVED",
}
