export enum PaymentTermType {
  DUE_ON_RECEIPT = "DUE_ON_RECEIPT",
  DUE_ON_DATE_SPECIFIED = "DUE_ON_DATE_SPECIFIED",
  NET_10 = "NET_10",
  NET_15 = "NET_15",
  NET_30 = "NET_30",
  NET_45 = "NET_45",
  NET_60 = "NET_60",
  NET_90 = "NET_90",
  NO_DUE_DATE = "NO_DUE_DATE",
}
