export enum TemplateFieldName {
  ITEMS_QUANTITY = "ITEMS_QUANTITY",
  ITEMS_DESCRIPTION = "ITEMS_DESCRIPTION",
  ITEMS_DATE = "ITEMS_DATE",
  ITEMS_DISCOUNT = "ITEMS_DISCOUNT",
  ITEMS_TAX = "ITEMS_TAX",
}
